# profiles/hcc/config.yml
executor: slurm
mode: default
jobs: 16

use-apptainer: true
apptainer-prefix: "/mnt/nrdstor/richlab/aliciarich/.apptainer"
apptainer-args: "--nv --bind /work,/lustre,/mnt/nrdstor,/home,/mnt/nrdstor/richlab/shared/dorado_models:/models,/mnt/nrdstor/richlab/shared/databases:/refdb"

slurm-logdir: "/mnt/nrdstor/richlab/shared/nanomb/.snakemake/slurm_logs"

default-resources:
  - mem_mb=8000
  - runtime=60
  - partition=batch
  - account=richlab
  - extra=""

envvars:
  - PROJ_ROOT
  - OUT_ROOT
  - WORK
  - NRDSTOR
  - SINGULARITY_TMPDIR
  - SINGULARITY_CACHEDIR
  - APPTAINER_TMPDIR
  - APPTAINER_CACHEDIR

latency-wait: 60
restart-times: 1
printshellcmds: true
verbose: true
