name: nanoasv
channels: [conda-forge, bioconda]
dependencies:
  - python=3.11
  - nanoasv=1.2.2     
  - r-base=4.3.*
  - r-optparse
  - r-tidyverse
  - r-data.table
  - r-ggplot2
  - bioconductor-phyloseq
  - r-readr
  - r-dplyr